import '../styles/globals.scss';
import Head from 'next/head';
import { AppProps } from 'next/app';

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Nikolay Stadnik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default App;
